config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
  	resources :comments
  end

  root 'posts#index'

  resources :users

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments

	validates :title, presence: true
	validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :find_post, only: [:edit, :update, :destroy]

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:comment))
		@comment.user_id = current_user.id if current_user

		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @comment.update(params[:comment].permit(:comment))
			redirect_to post_path(@post)
		else
			render 'edit'
		end
	end

	def destroy
		@comment.destroy
		redirect_to post_path(@post)
	end







	private

	def find_post
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts = Post.all.order(created_at: :desc)
	end

	def show
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to root_url
	end



	private

	def find_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :content)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = current_user
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.haml
.comment.clearfix
	.content
		%p.comment_content= comment.comment
		%p.comment_author= comment.user.email

	.buttons
		= link_to "Edit", edit_post_comment_path(comment.post, comment)
		= link_to "Delete", [comment.post, comment], method: :delete, data: {confirm: "Are You sure?"}

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build]) do |f|
	= f.input :comment, label: "New Post"
	= f.submit :Post

app/views/comments/edit.html.haml
%h1 Edit Reply

= simple_form_for([@post, @comment]) do |f|
	= f.input :comment, label: "Edit Post"
	= f.submit :confirm

app/views/layouts/application.html.haml
!!! 5

%html
%head
	%title Simple Rails Forum
	= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
	= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Lato:400,700,300"
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags

%body
	%header.main_header.clearfix
		.wrapper
			#logo
				%p= link_to "Simple Rails Forum", root_url
			#buttons
				- if user_signed_in?
					= link_to "Profile", current_user
					= link_to "New Post", new_post_path
					= link_to "Log out", destroy_user_session_path, method: :delete
				- else
					= link_to "Sign up", new_user_registration_path
					= link_to "Sign in", new_user_session_path

	.wrapper
		%p.notice= notice
		%p.alert= alert
	.wrapper
		=yield

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
	= f.input :title
	= f.input :content
	= f.submit

app/views/posts/edit.html.haml
%h1 Edit Post

= render 'form'

= link_to "Back", root_url

app/views/posts/index.html.haml
#posts
	.post
		- @posts.each do |post|
			%h2.title= link_to post.title, post
			%p.date
				Submited
				= time_ago_in_words(post.created_at)
				by
				= post.user.email

app/views/posts/new.html.haml
%h1 New Post

= render 'form'

= link_to "Back", root_url

app/views/posts/show.html.haml
#post_content
	%h2= @post.title
	%p= @post.content

	#comments
		%h2
			= @post.comments.count
			Posts
		= render @post.comments

		%h3 Reply to thread
		= render "comments/form"
		%br

	= link_to "Back", root_url, class: "button"
	= link_to "Edit", edit_post_path(@post), class: "button"
	= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are You sure?"}, class: "button"

app/views/users/show.html.haml
%h2= @user.email

- @user.posts.each do |post|
	%p= link_to post.title, post_path(post)